### ISSUE TITLE
get({ id, timeout}) does not respect timeout

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-ooo#5]
I haven't tested this (!) but reading [this code](https://github.com/ssbc/ssb-ooo/blob/master/index.js#L66-L69) it looks like we're not actually checking `opts.timeout` anywhere, whereas the readme specifies that the option is passed.

**Comment by dominictarr** [comment]
ssb-ooo is just a wrapper around [gossip-query](https://github.com/dominictarr/gossip-query), which handles the timeout: https://github.com/dominictarr/gossip-query/commit/9d00808f4b3ec97d8b96094dc50682993a1e00fe
